### ISSUE TITLE
No PaGroup58 Launched

### ISSUE THREAD

**Issue by AdrianHockey** [PaloAltoNetworks/aws-transit-vpc#13]
No PaGroup58 is getting launched, I am getting this invocation error for the Lambda function:

Expecting value: line 1 column 1 (char 0): JSONDecodeError
Traceback (most recent call last):
File "/var/task/cloudtrailLambda.py", line 98, in lambda_handler
parse_log(FILENAME)
File "/var/task/cloudtrailLambda.py", line 52, in parse_log
d = json.loads(f.read().decode("utf-8"))
File "/var/lang/lib/python3.6/json/__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "/var/lang/lib/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/var/lang/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AdrianHockey** [comment]
sorted itself out
